#!/bin/bash

_usageText="Usage: $0 [-h] [-s] [-u] wallpaperName"
_helpText="swww-wc wallpaper changer
\t A utility for easily managing and swappeing wallpapers with swww
\t -h Prints this help
\t -s Searches for system-wide wallpapers only
\t -u Searches for user wallpapers only
"

function usage() {
    printf $_usageText
    exit 1
}

function _help() {
    printf $_helpText
    exit 0
}

# Looks for files within a requested folder with filenames that match a given regex
# Ignores file extensions
# ARGS:
#       $1 - Nameref used to return the results array
#       $2 - Folder to be searched
#       $3 - Regex to match filenames against
function getFilesByName() {
    local -n foundFiles=$1
    readarray foundFiles < <(find $2 -mindepth 1 -iregex ".*\/[^.\/]*$3[^\/]*")
}

# Reads in flag arguments and translates them into internal status flags
declare sysOnly=false
declare usrOnly=false
while getopts ":hsu" opt; do
    case "${opt}" in
        h)
            _help
            ;;
        s)
            sysOnly=true
            ;;
        u)
            usrOnly=true
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# Grabs matching filepaths from requested locations
declare -a sysFilePaths=()
if [[ "$usrOnly" != true ]]; then
    getFilesByName sysFilePaths /usr/share/swww-wc/wallpapers $1
fi

declare -a usrFilePaths=()
if [[ "$sysOnly" != true  && -d ~/.wallpapers ]]; then
    getFilesByName usrFilePaths ~/.wallpapers $1
fi

filePaths=( "${sysFilePaths[@]}" "${usrFilePaths[@]}" )
resCount=${#filePaths[@]}

# No results found, program exits
if [ $resCount -le 0 ]; then
     printf "No wallpapers found\n"
    exit 0
# One result found, target is set implicitly
elif [ $resCount -eq 1 ]; then
    target=${filePaths[0]}
# Multiple results found, user is queried for selection
else
    printf "Multiple wallpapers found:\n"
    for index in $(seq 0 $((${resCount} - 1)))
    do
            fileName=$(basename ${filePaths[$index]})
            printf "$((${index} + 1))) ${fileName}\n"
    done
    read -p "Select wallpaper: " target
    if ! [[ $target =~ ^[0-9]+$ ]]; then
            printf "Err: Cannot interpret input as integer\n"
            exit 1
    fi
    target=${filePaths[$(($target - 1))]}
fi

# Calls swww to change background
(&>/dev/null swww img $target --resize crop --transition-type wipe --transition-angle 45 --transition-duration 1.5 &)
